# IMPORTANT: Before install mibew copy this file to config.yml and fill it with
# your own settings!


# MySQL Database parameters
database:
    host: ""
    port: 3306
    db: ""
    login: ""
    pass: ""
    tables_prefix: ""
    use_persistent_connection: false

# Mail
## This value will be used as sender address in all e-mails Mibew send.
mailbox: mibew@yourdomain.com

## Mailer parameters
mailer:
    # This value determines what kind of mailer will be used. Possible values
    # are "mail" and "smtp".
    #
    # To use standard PHP mail function just set this option to "mail". No
    # additional configs are required in this case.
    #
    # To use SMTP-based solution set this option "smtp". This approach require
    # some extra configuration to be done (see below).
    transport: mail

    # The lines below represents default SMTP mailer configurations. They will
    # be used only if the "transport" option is set to "smtp".
    host: localhost
    port: 25
    user: user
    pass: ""
    # The following option determines what kind of encryption should be used.
    # false means no encyption at all. Another values once can use are "ssl" and
    # "tls".
    encryption: false

# Locales
## Native name will be used in this locale
home_locale: en
## If user does not provide known lang
default_locale: en

# A timezone to use. Leave this value empty to use the default timezone from the
# system settings. For the details about available timezones see
# http://php.net/manual/en/timezones.php
timezone: ""

# Plugins
plugins: []

## Exapmle of plugins configuration
# plugins:
#     "VendorName:PluginName":
#         weight: 100
#         some_configurable_value: value
#     "VendorName:AnotherPluginName":
#         very_important_value: "$3.50"
